branches:
  only:
    - master

image:
  - Ubuntu2004

environment:
  GITHUB_API_KEY:
    secure: w1zaTUARBAuhkAKUke5sBvSkVtlDGL8YfQxROzv5oGIynVJImn+KWGFVDxyjQore

  global:
    HAXELIB_ROOT: /home/appveyor/haxelib
    HAXE_INSTALLDIR: /home/appveyor/haxe

install:
  - cd /home/appveyor
  - sudo add-apt-repository ppa:haxe/releases -y
  - sudo apt update
  - sudo apt install neko tar -y
  - wget https://github.com/HaxeFoundation/haxe/releases/download/4.2.4/haxe-4.2.4-linux64.tar.gz
  - mkdir $HAXE_INSTALLDIR
  - tar -xf haxe-4.2.4-linux64.tar.gz -C $HAXE_INSTALLDIR
  - export PATH=$PATH:$HAXE_INSTALLDIR/haxe_20211022152000_ab0c054
  - mkdir $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
  - haxelib install closure
  - haxelib list

build_script:
  - cd $APPVEYOR_BUILD_FOLDER
  
  # Build the pages
  - haxe dataslinger_example.hxml
  - haxe geometrize_installer.hxml
  - haxe geometrize_lib_example.hxml
  - haxe minimal_example.hxml

# Deploy the generated pages to the S3 buckets
#deploy:
#  - provider: s3
#    access_key_id: ${AWS_ACCESS_KEY_ID}
#    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
#    bucket: ${AWS_S3_GEOMETRIZE_INSTALLER_BUCKET_NAME}
#    local_dir: bin/geometrize_installer
#    skip_cleanup: true
#    acl: public_read
#  - provider: s3
#    access_key_id: ${AWS_ACCESS_KEY_ID}
#    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
#    bucket: ${AWS_S3_GEOMETRIZE_EXAMPLE_BUCKET_NAME}
#    local_dir: bin/geometrize_lib_example
#    skip_cleanup: true
#    acl: public_read
#  - provider: s3
#    access_key_id: ${AWS_ACCESS_KEY_ID}
#    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
#    bucket: ${AWS_S3_MINIMAL_EXAMPLE_BUCKET_NAME}
#    local_dir: bin/minimal_example
#    skip_cleanup: true
#    acl: public_read
#  - provider: s3
#    access_key_id: ${AWS_ACCESS_KEY_ID}
#    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
#    bucket: ${AWS_S3_DATASLINGER_EXAMPLE_BUCKET_NAME}
#    local_dir: bin/dataslinger_example
#    skip_cleanup: true
#    acl: public_read