sudo: required
dist: trusty
language: haxe

# Build the project
script:
  - haxe geometrize-s3-bucket-downloader.hxml release.hxml

# Deploy the generated pages to the Geometrize S3 buckets
deploy:
  - provider: s3
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    bucket: ${AWS_S3_GEOMETRIZE_INSTALLER_BUCKET_NAME}
    local_dir: bin/release
    skip_cleanup: true
    acl: public_read
  - provider: s3
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    bucket: ${AWS_S3_GEOMETRIZE_EXAMPLE_BUCKET_NAME}
    local_dir: bin/release
    skip_cleanup: true
    acl: public_read